# Generated by Django 4.0.5 on 2022-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.JSONField(blank=True, default='user'),
            preserve_default=False,
        ),
    ]
