# Generated by Django 4.0.5 on 2022-06-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_postproduct_options_alter_postproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.category'),
        ),
    ]
